config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'questions#index'
  get '/users/new', to: 'users#new', as: 'signup'
  get '/sessions/new', to: 'sessions#new', as: 'login'

  resources :users
  resources :sessions

  get 'tags/:tag', to: 'questions#index', as: :tag

  resources :questions do 
    resources :answers, except: [:index,:show,:new]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :update, Question do |question|
          question.user == user
        end
        can :destroy, Question do |question|
          question.user == user
        end
        can :update, Reply do |reply|
          reply.user == user
        end
        can :destroy, Reply do |reply|
          reply.user == user
        end
        can :create, Question
        can :create, Reply
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :user
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  code        :text
#  tag_id      :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Question < ApplicationRecord
    belongs_to :user
    has_many :answers
    validates :title, presence: true
    validates :description, presence: true
    acts_as_taggable
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_uniqueness_of :email
    has_many :questions, dependent: :destroy
    has_many :answers, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
  end

  def show
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    if @answer.save 
      redirect_to question_path(@question)
    else
      flash notice: "retry, error in posting answer"
      redirect_to question_path(@question)
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
     @question = Question.find(params[:question_id])
     @answer = Answer.find(params[:id])    
      if @answer.update(answer_params)
       redirect_to question_path(@question)
      else
        render :edit
      end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question)
  end
  private
  def answer_params
    params.require(:answer).permit(:description,:code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    current_user
  end

  def must_login?
    if !logged_in?
      flash[:alert]= "you must be logged"
      redirect_to root_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :must_login?, only: [:new, :edit, :destroy]
  # load_and_authorize_resource param_method: :my_sanitizer
  # load_and_authorize_resource

  def index
    if params[:tag]
      @questions = Question.tagged_with(params[:tag])
    else
      @questions = Question.all
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answers.new
  end

  def new
    @question = current_user.questions.build
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to root_path
  end
  private

  # def my_sanitizer
  #   params.require(:question).permit(:title,:description,:code,:tag_list)
  # end

  def question_params
    params.require(:question).permit(:title,:description,:code,:tag_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_url flash[:notice] = "logged in"
    else
      flash.now.alert = "Email or Password is incorrect"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url flash[:notice] = "logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_url flash[:notice] ="successfully Signed Up"
        else
            render :new
        end
    end

     private
    def user_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= render('layouts/errors', object: @answer)%>



<%= form_for [@question,@answer] do |f| %> 
      <div class="control-group">
        <%= f.label :description %>
      <div class="controls">
        <%= f.text_area :description, cols: 40, rows: 15 %>
      </div>
      </div>
      <div class="control-group">
        <%= f.label :code %>
      <div class="controls">
        <%= f.cktext_area :code, ckeditor: { language: 'english', width: 800}%>
      </div>
      </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit 'submit', class: 'btn btn-primary'%>
      </div>
    </div>
<% end %>

app/views/answers/edit.html.erb
<%= render 'form'%>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(object.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContentAidSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%#//ckeditor default ajax
  <script type='text/javascript' charset='UTF-8'>
  $(document).ready(function(){
    $('form[data-remote]').bind('ajax:before', function(){
      for (instance in CKEDITOR.instances){
        CKEDITOR.instances[instance].updateElement();
      }
    });
  });%>
</script>
  </head>

  <body>
  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Questions<span class="sr-only">(current)</span></a></li>
        <li><a href="#">Tags</a></li>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">Users</a></li>
        <% if current_user %>
        <li><%= link_to "Log Out", session_path(current_user), method: "delete" %></li>
        <li>logged:<%= current_user.name %></li>
      <% else %>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class=container>
    <%= flash[:notice]%>
    <%= flash[:alert]%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= render('layouts/errors', object: @question)%>



<%= form_for @question do |f| %>
  <div class="control-group">
      <%= f.label :title %>
      <div class="controls">
        <%= f.text_field :title %>
      </div>
      <div class="control-group">
      <%= f.label :description %>
      <div class="controls">
        <%= f.text_area :description, cols: 40, rows: 15 %>
      </div>
      </div>
      <div class="control-group">
      <%= f.label :code %>
      <div class="controls">
        <%= f.cktext_area :code, ckeditor: { language: 'english', width: 800}%>
      </div>
      </div>
      <div class="control-group">
      <%= f.label :tag_list, "Tags (separated by commas)" %>
      <div class="controls">
        <%= f.text_field :tag_list %>
      </div>
      </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit 'submit', class: 'btn btn-primary'%>
      </div>
    </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

<%= render 'form'%>

app/views/questions/index.html.erb
<div id="tag_cloud">
  <% tag_cloud Question.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>


<%= link_to "new question" ,new_question_path %>

<% if @questions.any? %>
   <% @questions.each do |question| %>
        <h4><%= question.user.name %></h4>
        <p><%= link_to question.title, question_path(question) %>
        <br /><br /><%= raw(question.code) %>&nbsp&nbsp<%= link_to "edit", edit_question_path(question)%>&nbsp<%= link_to "delete", question_path(question), data: {confirm: 'delete question?', method: :delete}%></p>
        <p>Tags: <%= raw(question.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></p>
     <% end %>
     <% else %>
     <h3>AAAiiii!!,hakuna questions bado!!</h3>
<% end %>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

<%= render 'form'%>

app/views/questions/show.html.erb
   <p> <%= @question.description%>
    <br />
        <%= raw(@question.code) %>
    </p>
   

    <% if @question.answers.any? %>
        <h5>Answers</h5>
        <ul>
        <% @question.answers.each do |answer| %>
            <li><%= answer.user_id %>
            <br />
            <%= answer.description %>
            <br />
            <%= raw(answer.code)%>
            <%= link_to "edit", edit_question_answer_path(@question)%>
            <%= link_to "delete", question_answer_path(@question), data:{confirm: "delete answer?", method: :delete}%>
            </li>
        <% end %>
        </ul>
        <% else %>
            <h5>there are no replies yet</h5>
    <% end %>
<p>Tags: <%= raw(@question.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></p>

    <%= render('layouts/errors', object: @answer)%>



    <%= form_for [@question,@answer] do |f| %> 
        <div class="control-group">
            <%= f.label :description %>
        <div class="controls">
            <%= f.text_area :description, cols: 80, rows: 3 %>
        </div>
        </div>
        <div class="control-group">
            <%= f.label :code %>
        <div class="controls">
            <%= f.cktext_area :code, ckeditor: { language: 'english', width: 700}%>
        </div>
        </div>
        <div class="control-group">
        <div class="controls">
            <%= f.submit 'submit', class: 'btn btn-primary'%>
        </div>
        </div>
    <% end %>

app/views/users/_form.html.erb
<%= render "layouts/errors", object: @user %>

<%= form_for @user do |f|%>
    <div class=field>
        <%= f.label :name %> <br />
        <%= f.text_field :name %>  
    </div>
    <div class=field>
        <%= f.label :email %> <br />
        <%= f.text_field :email %>  
    </div>
    <div class=field>
        <%= f.label :password %> <br />
        <%= f.password_field :password %>  
    </div>
    <div class=field>
        <%= f.label :password_confirmation %> <br />
        <%= f.password_field :password_confirmation %>  
    </div>
    <div class=action> <%= f.submit %></div>
<% end %>

app/views/users/new.html.erb
<h3>Welcome to sign up</h3>

<%= render "form" %>